{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}-pvc
spec:
  accessModes:
  - {{.Values.pvc.access}}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "1Gi" }}
{{- end}}