{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulset.service.name }}-service
  labels:
    {{- include "labelForSts" . | indent 3}}
spec:
  ports:
    - port: {{ .Values.statefulset.service.port }}
  clusterIP: None
  selector:
    app: {{ .Values.statefulset.name }}
{{- end}}